version: "3"
services:
  node-ocr:
    build: .
    networks:
      - back
    # ports:
      # - 3002:3000
  
  nginx:
    image: nginx:1.24-alpine
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "3000:80"
    networks:
      - back
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

networks:
  back:
    driver: bridge